name: Run test.py every 30 seconds
on:
  workflow_dispatch: 
  push:
    branches:
      - main 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install google-generativeai


      - name: Run script in loop
        run: |          
          python scripts/test.py
